Tildes y typos arreglados en el post
Salamanca2024/Blog pull request #1
Opened 2024-11-05 23:12 UTC by Salamanca2024

No debimos pasar este error a master.

2024-11-05 23:15 UTC, SantiagoSR-24 requested changes
En vez de tildes directas, usa entidades html

2024-11-05 23:23 UTC, Salamanca2024 commented
Cambios hechos, por favor hazme el merge

2024-11-05 23:24 UTC, SantiagoSR-24 approved these changes
Excelente, eso era

2024-11-05 23:26 UTC, merged

2024-11-06 18:18 UTC, Salamanca2024 reviewed
Ok